### ISSUE TITLE
App crashes  on opening in the stimulator (Sample keeps stopping)

### ISSUE THREAD

**Issue by brlivsky** [Tibolte/AgendaCalendarView#130]
`11-12 21:08:12.306 4095-4095/? E/memtrack: Couldn't load memtrack module (No such file or directory)
11-12 21:08:12.306 4095-4095/? E/android.os.Debug: failed to load memtrack module: -2
11-12 21:08:12.641 4114-4114/? E/memtrack: Couldn't load memtrack module (No such file or directory)
11-12 21:08:12.641 4114-4114/? E/android.os.Debug: failed to load memtrack module: -2
11-12 21:08:19.801 4126-4126/? E/memtrack: Couldn't load memtrack module (No such file or directory)
11-12 21:08:19.801 4126-4126/? E/android.os.Debug: failed to load memtrack module: -2
11-12 21:08:19.877 4153-4161/? E/art: Failed sending reply to debugger: Broken pipe
11-12 21:08:19.962 2096-2468/com.google.android.gms.persistent E/NetworkScheduler.SR: Unrecognised action provided: android.intent.action.PACKAGE_REMOVED
11-12 21:08:20.268 4170-4170/? E/memtrack: Couldn't load memtrack module (No such file or directory)
11-12 21:08:20.268 4170-4170/? E/android.os.Debug: failed to load memtrack module: -2
11-12 21:08:20.676 4243-4243/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.github.tibolte.sample, PID: 4243
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.tibolte.sample/com.github.tibolte.sample.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.tibolte.agendacalendarview.AgendaCalendarView.init(java.util.Locale, java.util.List, java.util.List, java.util.List, com.github.tibolte.agendacalendarview.CalendarPickerController)' on a null object reference
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.tibolte.agendacalendarview.AgendaCalendarView.init(java.util.Locale, java.util.List, java.util.List, java.util.List, com.github.tibolte.agendacalendarview.CalendarPickerController)' on a null object reference
                                                     at com.github.tibolte.sample.MainActivity.onCreate(MainActivity.java:73)
                                                     at android.app.Activity.performCreate(Activity.java:6662)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
11-12 21:08:36.123 1661-1673/system_process E/ActivityManager: applyOptionsLocked: Unknown animationType=0
11-12 21:08:36.146 4272-4277/? E/art: Failed sending reply to debugger: Broken pipe
11-12 21:08:36.511 4272-4272/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.github.tibolte.sample, PID: 4272
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.tibolte.sample/com.github.tibolte.sample.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.tibolte.agendacalendarview.AgendaCalendarView.init(java.util.Locale, java.util.List, java.util.List, java.util.List, com.github.tibolte.agendacalendarview.CalendarPickerController)' on a null object reference
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.tibolte.agendacalendarview.AgendaCalendarView.init(java.util.Locale, java.util.List, java.util.List, java.util.List, com.github.tibolte.agendacalendarview.CalendarPickerController)' on a null object reference
                                                     at com.github.tibolte.sample.MainActivity.onCreate(MainActivity.java:73)
                                                     at android.app.Activity.performCreate(Activity.java:6662)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
`

**Comment by AndroidDeveloperLB** [comment]
How did you succeed importing it?

**Comment by brlivsky** [comment]
Once extracting the downloded zip file opening it from android studio. (FILE - OPEN - LOCATION). On encountering each error googling it and rectfying them.

**Comment by AndroidDeveloperLB** [comment]
I meant how.
How did you handle the errors?
I get this one now:
https://github.com/Tibolte/AgendaCalendarView/issues/128

**Comment by DevNeeth** [comment]
I don't remember precisely. Have spend a lot of time digging the bugs but at the end nothing went successful.
