### ISSUE TITLE
Problem with LoadEvents

### ISSUE THREAD

**Issue by Doxoh** [Tibolte/AgendaCalendarView#150]
Hello I have the following problem:

This is my code to add new events on runtime:

```
@Override
public void onScrollToDate(Calendar calendar) {
    provider.fetchCalendarData(calendar.getTime());
    List<CalendarEvent> eventList = provicer.CalendarData(bestandsdaten.activeUCR).getEvents();
    CalendarManager.getInstance().loadEvents(eventList);
}
```

But I get this exeption:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: ***, PID: 25666
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getMeasuredHeight()' on a null object reference
                      at se.emilsjolander.stickylistheaders.StickyListHeadersListView.updateHeader(StickyListHeadersListView.java:355)
                      at se.emilsjolander.stickylistheaders.StickyListHeadersListView.updateOrClearHeader(StickyListHeadersListView.java:320)
                      at se.emilsjolander.stickylistheaders.StickyListHeadersListView.access$900(StickyListHeadersListView.java:37)
                      at se.emilsjolander.stickylistheaders.StickyListHeadersListView$WrapperListScrollListener.onScroll(StickyListHeadersListView.java:475)
```

Did you have an idea?

**Comment by Doxoh** [comment]
.
