### ISSUE TITLE
Error when Compiling with Azure mobile service module

### ISSUE THREAD

**Issue by PrakashJ12** [Tibolte/AgendaCalendarView#18]
When the module is with Azure mobile service module Error occures

compile 'com.microsoft.azure:azure-mobile-services-android-sdk:2.0.2'

Error Trace(Gradle Console):

:app:transformClassesWithDexForDebug

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/common/annotations/GwtCompatible;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_25\bin\java.exe'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by PrakashJ12** [comment]
On closer inspection I think problem is with the guava module

Agenda calendar does not work when compiled with this:
compile 'com.google.guava:guava:19.0'

How do I fix this.... ? Any help?

**Comment by PrakashJ12** [comment]
Hello, I see that the google collection library used (https://code.google.com/p/google-collections/) is no longer maintained and advices to replace collections by using Guava library(http://guava-libraries.googlecode.com/)

Why do you still depend on Google collections?

I think that is the root cause of the real problem.

**Comment by PrakashJ12** [comment]
I have made a pull request with the fix for this issue... Please review it.
https://github.com/Tibolte/AgendaCalendarView/pull/19

**Comment by Tibolte** [comment]
Merged
