### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ankit2771991** [Tibolte/AgendaCalendarView#20]
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
                                                                          at java.util.ArrayList.get(ArrayList.java:310)
                                                                          at com.github.tibolte.agendacalendarview.CalendarManager.getLastMonth(CalendarManager.java:318)
                                                                          at com.github.tibolte.agendacalendarview.CalendarManager.addWeekToLastMonth(CalendarManager.java:313)
                                                                          at com.github.tibolte.agendacalendarview.CalendarManager.buildCal(CalendarManager.java:217)
                                                                          at com.github.tibolte.agendacalendarview.AgendaCalendarView.init(AgendaCalendarView.java:190)

This error suddenly came with new year, before it the library was working fine

**Comment by tzanou** [comment]
Same here!
