### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1 for date

### ISSUE THREAD

**Issue by mapiko** [Tibolte/AgendaCalendarView#38]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: si.lamu.bikeshop, PID: 13253
                                                   java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
                                                       at com.loopj.android.http.AsyncHttpResponseHandler.onUserException(AsyncHttpResponseHandler.java:304)
                                                       at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:395)
                                                       at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
                                                       at java.util.ArrayList.get(ArrayList.java:310)
                                                       at com.github.tibolte.agendacalendarview.CalendarManager.getLastMonth(CalendarManager.java:319)
                                                       at com.github.tibolte.agendacalendarview.CalendarManager.addWeekToLastMonth(CalendarManager.java:314)
                                                       at com.github.tibolte.agendacalendarview.CalendarManager.buildCal(CalendarManager.java:218)
                                                       at com.github.tibolte.agendacalendarview.AgendaCalendarView.init(AgendaCalendarView.java:193)
                                                       at si.lamu.bikeshop.activity.AgendaActivity$1.onFinish(AgendaActivity.java:117)
                                                       at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:368)
                                                       at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by avgurf** [comment]
Yeah, this seems related to this issue: 
https://github.com/Tibolte/AgendaCalendarView/issues/37

**Comment by dilipappectual** [comment]
Not resolved at
