### ISSUE TITLE
InflateException On 4.3 (and possibly others)

### ISSUE THREAD

**Issue by t-howes** [Tibolte/AgendaCalendarView#73]
Hey,

Everything seems to work great on Lollipop and up, but on 4.3 (and maybe other older versions) I'm getting an InflateException when inflating my fragment containing the AgendaCalendarView.

In my fragment's onCreateView():
try {
      mScheduleFrag = inflater.inflate(R.layout.fragment_my_schedule, null, false);
} catch (InflateException e) {
      e.printStackTrace();
}

InflateException catch log: 
I/dalvikvm: Failed resolving Lcom/github/tibolte/agendacalendarview/AgendaCalendarView; interface 7982 'Lse/emilsjolander/stickylistheaders/StickyListHeadersListView$OnStickyHeaderChangedListener;'
W/dalvikvm: Link of class 'Lcom/github/tibolte/agendacalendarview/AgendaCalendarView;' failed
W/System.err: android.view.InflateException: Binary XML file line #11: Error inflating class com.github.tibolte.agendacalendarview.AgendaCalendarView
W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
W/System.err:     at MyScheduleFragment.onCreateView(MyScheduleFragment.java:80)

So there appears to be a problem with the stick headers dependency. Have you found or heard of anyone else having this issue on older devices? Any fixes? Beings the exception is thrown in onCreateView(), my mScheduleFrag is null and I end up with a blank fragment.

**Comment by hitesh-dhamshaniya** [comment]
FATAL EXCEPTION: main
  Process: com.devdigital.devcomm, PID: 16372
  android.view.InflateException: Binary XML file line #19: Error inflating class com.github.tibolte.agendacalendarview.AgendaCalendarView
   at android.view.LayoutInflater.createView(LayoutInflater.java:623)
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
   at com.devdigital.devcomm.calendar.CalendarFragment.onCreateView(CalendarFragment.java:69)
   at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
   at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
   at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
   at android.os.Handler.handleCallback(Handler.java:733)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:136)
   at android.app.ActivityThread.main(ActivityThread.java:5052)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
   at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.constructNative(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at android.view.LayoutInflater.createView(LayoutInflater.java:597)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
    at com.devdigital.devcomm.calendar.CalendarFragment.onCreateView(CalendarFragment.java:69) 
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974) 
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) 
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252) 
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742) 
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617) 
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517) 
    at android.os.Handler.handleCallback(Handler.java:733) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:136) 
    at android.app.ActivityThread.main(ActivityThread.java:5052) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:515) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
    at dalvik.system.NativeStart.main(Native Method) 

I am alos getting issue on Android 4.4.4

**Comment by albert0m** [comment]
I had to add 

compile 'se.emilsjolander:stickylistheaders:2.7.0'

to the dependencies

**Comment by t-howes** [comment]
Holy cow, I forgot about this post. Luckily I've had the problem solved, but still appreciate your reply. I think what solved my problem was that my app was multidexing correctly. After adding an Application class that extends MultiDexApplication, it seemed to have fixed a lot of issues. We are still using 2.5.2 on the sticky headers so I imagine the application class is what fixed it. Hope this helps anyone in the future.

**Comment by hitesh-dhamshaniya** [comment]
Why comment date wrong appears here, i.e. I have reported this issue in last week, but my post is dated "Oct 1, 2016" ? why so?
